name: Publicar no PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload para o PyPI
    runs-on: ubuntu-latest
    permissions:
      # Permissão necessária para o Trusted Publishing (OIDC) funcionar sem token!
      id-token: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar ferramentas de build
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Gerar build da distribuição
        run: python -m build

      - name: Publicar pacote no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1